import { TCharacter } from 'src/types/character';

export const CHARACTERS_ONE_PIECE: TCharacter[] = [
  { name: 'Monkey D. Luffy', img: 'https://onepiece.fandom.com/wiki/Monkey_D._Luffy/Anime_Image' },
  { name: 'Roronoa Zoro', img: 'https://onepiece.fandom.com/wiki/Roronoa_Zoro/Anime_Image' },
  { name: 'Nami', img: 'https://onepiece.fandom.com/wiki/Nami/Anime_Image' },
  { name: 'Usopp', img: 'https://onepiece.fandom.com/wiki/Usopp/Anime_Image' },
  { name: 'Sanji', img: 'https://onepiece.fandom.com/wiki/Sanji/Anime_Image' },
  {
    name: 'Tony Tony Chopper',
    img: 'https://onepiece.fandom.com/wiki/Tony_Tony_Chopper/Anime_Image',
  },
  { name: 'Nico Robin', img: 'https://onepiece.fandom.com/wiki/Nico_Robin/Anime_Image' },
  { name: 'Franky', img: 'https://onepiece.fandom.com/wiki/Franky/Anime_Image' },
  { name: 'Brook', img: 'https://onepiece.fandom.com/wiki/Brook/Anime_Image' },
  { name: 'Jinbe', img: 'https://onepiece.fandom.com/wiki/Jinbe/Anime_Image' },
  { name: 'Portgas D. Ace', img: 'https://onepiece.fandom.com/wiki/Portgas_D._Ace/Anime_Image' },
  { name: 'Shanks', img: 'https://onepiece.fandom.com/wiki/Shanks/Anime_Image' },
  { name: 'Buggy', img: 'https://onepiece.fandom.com/wiki/Buggy/Anime_Image' },
  { name: 'Dracule Mihawk', img: 'https://onepiece.fandom.com/wiki/Dracule_Mihawk/Anime_Image' },
  { name: 'Boa Hancock', img: 'https://onepiece.fandom.com/wiki/Boa_Hancock/Anime_Image' },
  {
    name: 'Trafalgar D. Water Law',
    img: 'https://onepiece.fandom.com/wiki/Trafalgar_D._Water_Law/Anime_Image',
  },
  { name: 'Eustass Kid', img: 'https://onepiece.fandom.com/wiki/Eustass_Kid/Anime_Image' },
  {
    name: 'Donquixote Doflamingo',
    img: 'https://onepiece.fandom.com/wiki/Donquixote_Doflamingo/Anime_Image',
  },
  { name: 'Kaido', img: 'https://onepiece.fandom.com/wiki/Kaido/Anime_Image' },
  { name: 'Big Mom', img: 'https://onepiece.fandom.com/wiki/Charlotte_Linlin/Anime_Image' },
  { name: 'Blackbeard', img: 'https://onepiece.fandom.com/wiki/Marshall_D._Teach/Anime_Image' },
  { name: 'Sabo', img: 'https://onepiece.fandom.com/wiki/Sabo/Anime_Image' },
  { name: 'Gol D. Roger', img: 'https://onepiece.fandom.com/wiki/Gol_D._Roger/Anime_Image' },
  {
    name: 'Silvers Rayleigh',
    img: 'https://onepiece.fandom.com/wiki/Silvers_Rayleigh/Anime_Image',
  },
  { name: 'Crocodile', img: 'https://onepiece.fandom.com/wiki/Crocodile/Anime_Image' },
  { name: 'Smoker', img: 'https://onepiece.fandom.com/wiki/Smoker/Anime_Image' },
  { name: 'Tashigi', img: 'https://onepiece.fandom.com/wiki/Tashigi/Anime_Image' },
  { name: 'Koby', img: 'https://onepiece.fandom.com/wiki/Koby/Anime_Image' },
  { name: 'Helmeppo', img: 'https://onepiece.fandom.com/wiki/Helmeppo/Anime_Image' },
  { name: 'Arlong', img: 'https://onepiece.fandom.com/wiki/Arlong/Anime_Image' },
  { name: 'Rob Lucci', img: 'https://onepiece.fandom.com/wiki/Rob_Lucci/Anime_Image' },
  { name: 'Spandam', img: 'https://onepiece.fandom.com/wiki/Spandam/Anime_Image' },
  { name: 'Enel', img: 'https://onepiece.fandom.com/wiki/Enel/Anime_Image' },
  { name: 'Magellan', img: 'https://onepiece.fandom.com/wiki/Magellan/Anime_Image' },
  { name: 'Ivankov', img: 'https://onepiece.fandom.com/wiki/Emporio_Ivankov/Anime_Image' },
  { name: 'Kuzan (Aokiji)', img: 'https://onepiece.fandom.com/wiki/Kuzan/Anime_Image' },
  { name: 'Borsalino (Kizaru)', img: 'https://onepiece.fandom.com/wiki/Borsalino/Anime_Image' },
  { name: 'Sengoku', img: 'https://onepiece.fandom.com/wiki/Sengoku/Anime_Image' },
  { name: 'Garp', img: 'https://onepiece.fandom.com/wiki/Monkey_D._Garp/Anime_Image' },
  { name: 'Caesar Clown', img: 'https://onepiece.fandom.com/wiki/Caesar_Clown/Anime_Image' },
  { name: 'Shiryu', img: 'https://onepiece.fandom.com/wiki/Shiryu/Anime_Image' },
  { name: 'Perona', img: 'https://onepiece.fandom.com/wiki/Perona/Anime_Image' },
  { name: 'Bartolomeo', img: 'https://onepiece.fandom.com/wiki/Bartolomeo/Anime_Image' },
  { name: 'Carrot', img: 'https://onepiece.fandom.com/wiki/Carrot/Anime_Image' },
  { name: 'Pedro', img: 'https://onepiece.fandom.com/wiki/Pedro/Anime_Image' },
  { name: 'Vivi', img: 'https://onepiece.fandom.com/wiki/Nefertari_Vivi/Anime_Image' },
  { name: 'Pell', img: 'https://onepiece.fandom.com/wiki/Pell/Anime_Image' },
  { name: 'Wapol', img: 'https://onepiece.fandom.com/wiki/Wapol/Anime_Image' },
  { name: 'Rebecca', img: 'https://onepiece.fandom.com/wiki/Rebecca/Anime_Image' },
];

export const CHARACTERS_ARCANE: TCharacter[] = [
  {
    name: 'Vi',
    img: 'https://i.pinimg.com/736x/87/2f/20/872f20b13b4aa10a4b0006b08b6b89b7.jpg',
    alias: 'Piltover Enforcer',
    description: 'Big sis',
  },
  {
    name: 'Jinx',
    img: 'https://i.pinimg.com/736x/18/3f/bc/183fbc59efd79a339ffa32eee63715fc.jpg',
    alias: 'Zaun Chaos',
    description: 'Its me!',
    quote: 'Don\'t cry. You\'re perfect'
  },
  {
    name: 'Caitlyn',
    img: 'https://i.pinimg.com/736x/cd/3f/86/cd3f86296f9b8657451df523a3376565.jpg',
    alias: 'Sheriff',
    description: 'Cupcake?',
  },
  {
    name: 'Jayce',
    img: 'https://i.pinimg.com/1200x/02/44/e9/0244e9f2e7f273845b46b3480d2de64a.jpg',
    alias: 'The Person of Progress',
  },
  {
    name: 'Ekko',
    img: 'https://i.pinimg.com/1200x/d2/35/c4/d235c4fedefa0eb02dbd429d3d0d0e8f.jpg',
    alias: 'Time Punk',
    description: 'Boy Savior!',
  },
  {
    name: 'Heimerdinger',
    img: 'https://i.pinimg.com/736x/a1/50/85/a15085dae612abd9fdaa9550ae2d5b21.jpg',
    alias: 'Proffessor',
  },
  {
    name: 'Viktor',
    img: 'https://i.pinimg.com/736x/fd/b1/54/fdb154d94a8d4bab2faff838d9254399.jpg',
    alias: 'Hexcore Mind',
  },
  {
    name: 'Silco',
    img: 'https://i.pinimg.com/1200x/e9/78/85/e9788546d25a8a069fd995e4b1b5880b.jpg',
    alias: 'Zaun King',
    description: 'Also...dad',
  },
  {
    name: 'Mel Medarda',
    img: 'https://i.pinimg.com/736x/04/3f/11/043f112c28f9c7b5430611aa4cdb6e6c.jpg',
    alias: 'Golden Mind',
  },
  {
    name: 'Sevika',
    img: 'https://i.pinimg.com/736x/c7/d3/58/c7d3588422ca8223e09d729fbc6bbea6.jpg',
    alias: 'Zaun Fist',
    description: 'Metal arm',
  },
  {
    name: 'Vander',
    img: 'https://i.pinimg.com/736x/75/4d/51/754d51ab662503e612615e46a4aea5eb.jpg',
    alias: 'Undercity Dad',
    description: 'Dad',
  },
  {
    name: 'Marcus',
    img: 'https://i.pinimg.com/736x/fd/92/ed/fd92ed05b5649e5514ac85c126072019.jpg',
    alias: 'Dirty Cop',
    description: 'Snitch!!',
  },
  {
    name: 'Isha',
    img: 'https://i.pinimg.com/736x/77/f2/4d/77f24d72d12d117effe1565bce7f5d48.jpg',
    alias: 'Zaun Kid',
    description: 'My kid!',
  },
  {
    name: 'Claggor',
    img: 'https://i.pinimg.com/736x/f0/fe/ca/f0feca8428a7154cd1219de73948db1c.jpg',
    alias: 'Big Bro',
  },
  {
    name: 'Finn',
    img: 'https://i.pinimg.com/1200x/20/fc/32/20fc32c11a3ed4759987ed26c29fede6.jpg',
    alias: 'Shimmer Rat',
  },
  {
    name: 'Ambessa Medarda',
    img: 'https://i.pinimg.com/736x/17/21/28/17212887c89d8dc4e84331238359748c.jpg',
    alias: 'War Queen',
  },
  {
    name: 'Sky',
    img: 'https://i.pinimg.com/736x/9d/b1/eb/9db1eb4c3e9545113826c695c1e2e3e9.jpg',
    alias: 'Lab Ghost',
  },
  {
    name: 'Benzo',
    img: 'https://i.pinimg.com/736x/39/c6/d2/39c6d2b0ca724f7b02b897bda6375b77.jpg',
    alias: 'Fixer Guy',
  },
  {
    name: 'Huck',
    img: 'https://i.pinimg.com/736x/16/b6/f5/16b6f59bd40e37cc16987dd14aaeb067.jpg',
    alias: 'Shimmer Junk',
  },
  {
    name: 'Renni',
    img: 'https://i.pinimg.com/736x/1b/38/71/1b38718cca46aa66fa50e0221396a577.jpg',
    alias: 'Bar Boss',
  },
  {
    name: 'Hoskel',
    img: 'https://i.pinimg.com/736x/fb/58/1d/fb581d4fc6599eb6012e9e37b0f50882.jpg',
    alias: 'Council Suit',
  },
  {
    name: 'Salo',
    img: 'https://i.pinimg.com/736x/be/84/31/be843162f7e2a9a3b8daf1ea96eb04a2.jpg',
    alias: 'Council Suit',
  },
  {
    name: 'Bolbok',
    img: 'https://i.pinimg.com/736x/15/5a/2c/155a2c92067fc6d572e72cc6c9ae43e3.jpg',
    alias: 'Council Bot',
  },
  {
    name: 'Maddie',
    img: 'https://i.pinimg.com/1200x/12/6d/0a/126d0afb19b6a8623332fa1121f6033f.jpg',
    alias: 'Enforcer',
    description: 'Who Dis??',
  },
  {
    name: 'Singed',
    img: 'https://i.pinimg.com/736x/86/8f/e9/868fe9b0f136731867a453b5bc65d00f.jpg',
    alias: 'Mad Chemist',
    description: 'VeryBad!!',
  },
];
